services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=docker
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nikola
      POSTGRES_DB: dd_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
