"""Added description field to Box and Polygon

Revision ID: 2b1105cb6d69
Revises: a9713f145129
Create Date: 2025-05-12 11:41:06.939610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b1105cb6d69'
down_revision = 'a9713f145129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    with op.batch_alter_table('polygons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polygons', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('boxes', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
