"""Adde models for shapes

Revision ID: a9713f145129
Revises: 664454104484
Create Date: 2025-05-10 15:34:52.327253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9713f145129'
down_revision = '664454104484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x_point', sa.Float(), nullable=False),
    sa.Column('y_point', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polygons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x_point', sa.Float(), nullable=False),
    sa.Column('y_point', sa.Float(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('polygon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['polygon_id'], ['polygons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('annotation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annotation', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.drop_table('points')
    op.drop_table('polygons')
    op.drop_table('boxes')
    # ### end Alembic commands ###
